modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "https://github.com/Suff99/WhoCosmetics/blob/master/LICENSE"

[[mods]]
modId = "whocosmetics"
version = "${version}"
displayName = "WhoCosmetics"
authors = "EndPhoenix, Violet, Vespa, Teacup"
description = '''
Adds different clothing from the popular television series, Doctor Who
'''
#logoFile = ""

[[dependencies.whocosmetics]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.whocosmetics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
